### ISSUE TITLE
ranker data

### ISSUE THREAD

**Issue by chijames** [moutaigua8183/BookQA#3]
Hi,

Thanks for sharing the ranker code. I have several questions regarding the ranker data:
1. Why is the data in NLI format? Specifically, why do we have entailment and contradiction as the labels?
2. Is it possible to share the rouge-L filter code you used to construct distant supervision data?

Thanks.

**Comment by moutaigua8183** [comment]
To answer your questions:
1. It is only because we customize the codes based on Huggingface implementation which originally reads the NLI datasts. Our ranker is basically a binary classifier, so we use entailment as the positive label and contradiction as the negative label.
2. The codes for Rouge-L filter will less likely to be ready to release recently. However, I just submit a quick patch to the `nlpeval_helper.py` in `evaluation` folder.  You could  use `compute_rolling_rouge_L()` to measure the quality of each candidate passage in terms of your query.

Thanks!

**Comment by chijames** [comment]
Thank you so much!

**Comment by chijames** [comment]
Hi,

In the compute_rolling_rouge_L function, shouldn't ln 112: 
`summary_subseqs = zip(*(summary_toks[i : ] for i in range(len(ref_toks))))` be 
`summary_subseqs = zip(*(summary_toks[i : i+len(ref_toks)] for i in range(len(ref_toks))))`?
as per the formulas of rouge-L filter.

Thanks.

**Comment by moutaigua8183** [comment]
> Hi,
> 
> In the compute_rolling_rouge_L function, shouldn't ln 112:
> `summary_subseqs = zip(*(summary_toks[i : ] for i in range(len(ref_toks))))` be
> `summary_subseqs = zip(*(summary_toks[i : i+len(ref_toks)] for i in range(len(ref_toks))))`?
> as per the formulas of rouge-L filter.
> 
> Thanks.

It should be correct.   You can check the value of `hypo_dict` after that line.
